export const postsFromServer = [
  {
    id: 1,
    photoId: 1,
    date: 'Feb 23',
    minRead: 8,
    title: 'Watering mastery',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 2,
    photoId: 2,
    date: 'Feb 23',
    minRead: 8,
    title: 'Plant pot secrets',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 3,
    photoId: 3,
    date: 'Feb 23',
    minRead: 8,
    title: 'Professional Repot',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 4,
    photoId: 1,
    date: 'Feb 23',
    minRead: 8,
    title: 'Watering mastery',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 5,
    photoId: 3,
    date: 'Feb 23',
    minRead: 8,
    title: 'Professional Repot',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 6,
    photoId: 2,
    date: 'Feb 23',
    minRead: 8,
    title: 'Plant pot secrets',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 7,
    photoId: 2,
    date: 'Feb 23',
    minRead: 8,
    title: 'Plant pot secrets',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 8,
    photoId: 3,
    date: 'Feb 23',
    minRead: 8,
    title: 'Professional Repot',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 9,
    photoId: 1,
    date: 'Feb 23',
    minRead: 8,
    title: 'Watering mastery',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 10,
    photoId: 3,
    date: 'Feb 23',
    minRead: 8,
    title: 'Professional Repot',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 11,
    photoId: 1,
    date: 'Feb 23',
    minRead: 8,
    title: 'Watering mastery',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    id: 12,
    photoId: 2,
    date: 'Feb 23',
    minRead: 8,
    title: 'Plant pot secrets',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
];
